apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: hellok8s
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: hellok8s
    spec:
      ttlSecondsAfterFinished: 5
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - echo "hello k8s"; sleep 2;
            image: busybox:latest
            name: hellok8s
            resources: {}
          restartPolicy: Never
  schedule: '*/1 * * * *'
status: {}
