apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: hellok8s
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo "hello k8s" && sleep 2
        image: busybox:latest
        name: hellok8s
        resources: {}
      restartPolicy: Never
  backoffLimit: 6
  completions: 2
  parallelism: 1
  ttlSecondsAfterFinished: 10
status: {}
