apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testpod
  name: testpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testpod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testpod
    spec:
      containers:
        - command: ["sh", "-c", "date >>/data/out.txt"]
          image: busybox
          name: busybox
          volumeMounts:
            - name: "testlv"
              mountPath: "/data"
          resources: {}
      volumes:
        - name: "testlv"
          persistentVolumeClaim:
            claimName: testpvc
